apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    additionalArguments:
    - "--entrypoints.udp-dns.address=:53/udp"
    - "--entrypoints.tcp-dns.address=:53/tcp"
    ports:
      udp-dns:
        port: 53
        exposedPort: 53
        expose: true
        protocol: UDP
  entryPoints:
    udp-dns:
      address: ':53/udp'
