---
apiVersion: v1
kind: Service
metadata:
  name: pihole
spec:
  selector:
    app: pihole
  ports:
  - port: 8008
    targetPort: 80
    name: pihole-admin
  - port: 5355
    targetPort: 53
    protocol: UDP
    name: udp-dns
  - port: 5354
    targetPort: 53
    protocol: TCP
    name: tcp-dns
