---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: pihole-ingress
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/`)
      kind: Rule
      services:
        - name: pihole
          port: 8008
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: pihole-dns-tcp-ingress
spec:
  entryPoints:
    - tcp-dns
  routes:
    - match: HostSNI(`*`)
      services:
        - name: pihole
          port: 5354
          weight: 10
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteUDP
metadata:
  name: pihole-dns-udp-ingress
spec:
  entryPoints:
    - udp-dns
  routes:
    - services:
        - name: pihole
          port: 5355
          weight: 10
