apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    rbac.enabled: true
    metrics.prometheus.enabled: true
    kubernetes.ingressEndpoint.useDefaultPublishedService: true
    ssl:
      insecureSkipVerify: true
      enabled: true
      permanentRedirect: false
    dashboard:
      enabled: "true"
      domain: "traefik.localhost"
    additionalArguments:
    - "--entrypoints.tcp-dns.address=:5335/tcp"
    - "--entrypoints.udp-dns.address=:5335/udp"
    ports:
      udp-dns:
        port: 5335
        exposedPort: 5335
        expose: true
        protocol: UDP
      tcp-dns:
        port: 5335
        exposedPort: 5335
        expose: true
        protocol: TCP 
  entryPoints:
    udp-dns:
      address: ':5335/udp'
    tcp-dns:
      address: ':5335/tcp'
